<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>SQLite-like CRUD Application</title>';
echo '<style>';
echo 'body {';
echo 'color: blue;';
echo 'background-color: aqua;';
echo 'font-family: sans-serif;';
echo 'margin: 20px;';
echo 'margin: 20px;';
echo 'text-align: center;';
echo '}';
echo '.container { max-width: 800px; margin: auto; }';
echo '.form-container { margin-bottom: 20px; padding: 15px; border: 1px solid #ccc; border-radius: 5px; }';
echo 'input, button { padding: 8px; margin-top: 5px; }';
echo 'table { width: 100%; border-collapse: collapse; margin-top: 20px; }';
echo 'th, td { border: 1px solid #ccc; padding: 10px; text-align: left; }';
echo '.actions button { margin-right: 5px; }';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<h1>Task Manager</h1>';
echo '';
echo '<!-- Form for Insert/Update -->';
echo '<div class="form-container">';
echo '<h2>Add/Update Task</h2>';
echo '<input type="hidden" id="taskId">';
echo '<input type="text" id="taskText" placeholder="Enter task description" required>';
echo '<input type="number" id="taskPriority" placeholder="Priority (1-10)" min="1" max="10" required>';
echo '<input type="date" id="taskDueDate" required>';
echo '<button onclick="saveTask()">Save Record</button>';
echo '<button onclick="clearForm()">Cancel Update</button>';
echo '</div>';
echo '';
echo '<!-- Display Records -->';
echo '<h2>Current Records</h2>';
echo '<table>';
echo '<thead>';
echo '<tr>';
echo '<th>ID</th>';
echo '<th>Task Description (TEXT)</th>';
echo '<th>Priority (NUMBER)</th>';
echo '<th>Due Date (DATE)</th>';
echo '<th>Actions</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody id="recordTableBody">';
echo '<!-- Records will be inserted here by JavaScript -->';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '';
echo '<script>';
echo '// Use localStorage to simulate a persistent database for this client-side example';
echo 'const DB_KEY = 'tasksDB';';
echo 'let records = JSON.parse(localStorage.getItem(DB_KEY)) || [];';
echo 'let currentId = records.length > 0 ? Math.max(...records.map(r => r.id)) + 1 : 1;';
echo '';
echo 'function saveToDB() {';
echo 'localStorage.setItem(DB_KEY, JSON.stringify(records));';
echo 'displayRecords();';
echo '}';
echo '';
echo 'function clearForm() {';
echo 'document.getElementById('taskId').value = '';';
echo 'document.getElementById('taskText').value = '';';
echo 'document.getElementById('taskPriority').value = '';';
echo 'document.getElementById('taskDueDate').value = '';';
echo '}';
echo '';
echo '// INSERT and UPDATE operation';
echo 'function saveTask() {';
echo 'const id = document.getElementById('taskId').value;';
echo 'const text = document.getElementById('taskText').value;';
echo 'const priority = parseInt(document.getElementById('taskPriority').value);';
echo 'const dueDate = document.getElementById('taskDueDate').value;';
echo '';
echo 'if (!text || !priority || !dueDate) {';
echo 'alert('Please fill in all fields.');';
echo 'return;';
echo '}';
echo '';
echo 'if (id) {';
echo '// Update existing record';
echo 'const index = records.findIndex(r => r.id == id);';
echo 'if (index !== -1) {';
echo 'records[index].text = text;';
echo 'records[index].priority = priority;';
echo 'records[index].dueDate = dueDate;';
echo '}';
echo '} else {';
echo '// Insert new record';
echo 'records.push({';
echo 'id: currentId++,';
echo 'text: text,';
echo 'priority: priority,';
echo 'dueDate: dueDate';
echo '});';
echo '}';
echo 'saveToDB();';
echo 'clearForm();';
echo '}';
echo '';
echo '// DELETE operation';
echo 'function deleteTask(id) {';
echo 'if (confirm('Are you sure you want to delete this record?')) {';
echo 'records = records.filter(r => r.id !== id);';
echo 'saveToDB();';
echo '}';
echo '}';
echo '';
echo '// READ operation and display';
echo 'function displayRecords() {';
echo 'const tbody = document.getElementById('recordTableBody');';
echo 'tbody.innerHTML = '';';
echo 'records.sort((a, b) => a.id - b.id).forEach(record => {';
echo 'const row = tbody.insertRow();';
echo 'row.innerHTML = `';
echo '<td>${record.id}</td>';
echo '<td>${record.text}</td>';
echo '<td>${record.priority}</td>';
echo '<td>${record.dueDate}</td>';
echo '<td class="actions">';
echo '<button onclick="editTask(${record.id})">Edit</button>';
echo '<button onclick="deleteTask(${record.id})">Delete</button>';
echo '</td>';
echo '`;';
echo '});';
echo '}';
echo '';
echo '// Helper function to load data into the form for editing';
echo 'function editTask(id) {';
echo 'const record = records.find(r => r.id === id);';
echo 'if (record) {';
echo 'document.getElementById('taskId').value = record.id;';
echo 'document.getElementById('taskText').value = record.text;';
echo 'document.getElementById('taskPriority').value = record.priority;';
echo 'document.getElementById('taskDueDate').value = record.dueDate;';
echo '}';
echo '}';
echo '';
echo '// Initial display when the page loads';
echo 'displayRecords();';
echo '</script>';
echo '</body>';
echo '</html>';
?>