<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTFs-8">';
echo '<title>Login & Register</title>';
echo '<style>';
echo 'body {';
echo 'color: blue;';
echo 'background-color: aqua;';
echo 'font-family: sans-serif;';
echo 'display: flex;';
echo 'gap: 50px;';
echo 'justify-content: center;';
echo 'margin-top: 50px;';
echo '}';
echo 'form {';
echo 'border: 1px solid #ccc;';
echo 'padding: 20px;';
echo 'border-radius: 8px;';
echo '}';
echo 'input {';
echo 'display: block;';
echo 'margin-bottom: 10px;';
echo 'width: 200px;';
echo 'padding: 8px;';
echo '}';
echo 'button {';
echo 'width: 100%;';
echo 'padding: 10px;';
echo 'background: #007bff;';
echo 'color: white;';
echo 'border: none;';
echo 'cursor: pointer;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<!-- Login Form -->';
echo '<section>';
echo '<h2>Login</h2>';
echo '<form action="/login" method="POST">';
echo '<input type="text" name="username" placeholder="Username" required>';
echo '<input type="password" name="password" placeholder="Password" required>';
echo '<button type="submit">Login</button>';
echo '</form>';
echo '</section>';
echo '';
echo '<!-- Registration Form -->';
echo '<section>';
echo '<h2>Register</h2>';
echo '<form action="/register" method="POST">';
echo '<input type="text" name="username" placeholder="New Username" required>';
echo '<input type="password" name="password" placeholder="New Password" required>';
echo '<button type="submit">Create Account</button>';
echo '</form>';
echo '</section>';
echo '</body>';
echo '</html>';
?>