<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Dog Rescue Application</title>';
echo '<style>';
echo '/* Centers everything on the page */';
echo 'body {';
echo 'color: blue;';
echo 'font-family: Arial, sans-serif;';
echo 'display: flex;';
echo 'flex-direction: column;';
echo 'align-items: center;';
echo 'text-align: center;';
echo 'background-color: aqua;';
echo 'padding: 20px;';
echo '}';
echo '.container {';
echo 'background: white;';
echo 'padding: 20px;';
echo 'border-radius: 8px;';
echo 'box-shadow: 0 4px 8px rgba(0,0,0,0.1);';
echo 'width: 80%;';
echo 'max-width: 600px;';
echo '}';
echo 'input, button {';
echo 'margin: 10px;';
echo 'padding: 10px;';
echo 'width: 80%;';
echo '}';
echo 'table {';
echo 'border-collapse: collapse;';
echo 'width: 100%;';
echo 'margin-top: 20px;';
echo '}';
echo 'th, td {';
echo 'border: 1px solid #ddd;';
echo 'padding: 8px;';
echo '}';
echo '.error {';
echo 'color: red;';
echo 'font-weight: bold;';
echo 'margin-top: 10px;';
echo 'display: none;';
echo '}';
echo '.btn-quit {';
echo 'background-color: #ff4d4d;';
echo 'color: white;';
echo 'border: none;';
echo 'cursor: pointer;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="container" id="app">';
echo '<h1>Dog Rescue Registry</h1>';
echo '';
echo '<!-- Dog Entry Form -->';
echo '<input type="text" id="dogName" placeholder="Dog Name">';
echo '<input type="text" id="dogBreed" placeholder="Breed">';
echo '<input type="number" id="dogAge" placeholder="Age (years)">';
echo '<input type="number" id="dogWeight" placeholder="Weight (lbs)">';
echo '<button onclick="submitDog()">Submit Dog</button>';
echo '<button class="btn-quit" onclick="quitApp()">Quit Application</button>';
echo '';
echo '<hr>';
echo '';
echo '<!-- Search Section -->';
echo '<h3>Search for a Dog</h3>';
echo '<input type="text" id="searchQuery" placeholder="Enter dog name to search...">';
echo '<button onclick="searchDog()">Search</button>';
echo '<p id="errorMessage" class="error">No dog found with that name.</p>';
echo '';
echo '<!-- Three Required Empty Tables -->';
echo '<h3>Rescue Records</h3>';
echo '<table id="table1"><thead><tr><th>Name</th><th>Breed</th><th>Age</th><th>Weight</th></tr></thead><tbody id="tbody1"></tbody></table>';
echo '<br>';
echo '<table id="table2"><thead><tr><th>Search History/Details</th></tr></thead><tbody id="tbody2"></tbody></table>';
echo '<br>';
echo '</div>';
echo '';
echo '<script>';
echo 'const dogs = [];';
echo '';
echo 'function submitDog() {';
echo 'const name = document.getElementById('dogName').value;';
echo 'const breed = document.getElementById('dogBreed').value;';
echo 'const age = document.getElementById('dogAge').value;';
echo 'const weight = document.getElementById('dogWeight').value;';
echo '';
echo 'if (name && breed && age && weight) {';
echo 'const dog = { name, breed, age, weight };';
echo 'dogs.push(dog);';
echo '';
echo '// Add to the first table';
echo 'const tbody = document.getElementById('tbody1');';
echo 'const row = tbody.insertRow();';
echo 'row.innerHTML = `<td>${name}</td><td>${breed}</td><td>${age}</td><td>${weight}</td>`;';
echo '';
echo '// Clear inputs';
echo 'document.querySelectorAll('input').forEach(input => input.value = '');';
echo '} else {';
echo 'alert("Please fill in all fields.");';
echo '}';
echo '}';
echo '';
echo 'function searchDog() {';
echo 'const query = document.getElementById('searchQuery').value.toLowerCase();';
echo 'const errorMsg = document.getElementById('errorMessage');';
echo 'const found = dogs.find(dog => dog.name.toLowerCase() === query);';
echo '';
echo 'if (found) {';
echo 'errorMsg.style.display = 'none';';
echo 'const tbody2 = document.getElementById('tbody2');';
echo 'const row = tbody2.insertRow();';
echo 'row.innerHTML = `<td>Found: ${found.name} (${found.breed})</td>`;';
echo '} else {';
echo 'errorMsg.style.display = 'block'; // Shows error if no dog found';
echo '}';
echo '}';
echo '';
echo 'function quitApp() {';
echo 'if (confirm("Are you sure you want to quit?")) {';
echo 'document.getElementById('app').innerHTML = "<h2>Program Terminated.</h2><p>Refresh to restart.</p>";';
echo '}';
echo '}';
echo '</script>';
echo '';
echo '</body>';
echo '</html>';
?>