<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>REST API Simulation CRUD</title>';
echo '<style>';
echo 'body {';
echo 'color: blue;';
echo 'background-color: aqua;';
echo 'font-family: sans-serif;';
echo 'max-width: 800px;';
echo 'margin: 20px auto;';
echo 'padding: 0 20px;';
echo 'text-align: center;';
echo '}';
echo 'form {';
echo 'background: #f4f4f4;';
echo 'padding: 15px;';
echo 'border-radius: 5px;';
echo 'margin-bottom: 20px;';
echo '}';
echo 'input {';
echo 'margin-bottom: 10px;';
echo 'padding: 8px;';
echo 'width: 100%;';
echo 'box-sizing: border-box;';
echo '}';
echo 'button {';
echo 'padding: 10px 15px;';
echo 'cursor: pointer;';
echo 'background: #007bff;';
echo 'color: white;';
echo 'border: none;';
echo 'border-radius: 3px;';
echo '}';
echo 'button.delete {';
echo 'background: #dc3545;';
echo 'margin-left: 5px;';
echo '}';
echo 'button.edit {';
echo 'background: #ffc107;';
echo 'color: black;';
echo '}';
echo 'table {';
echo 'width: 100%;';
echo 'border-collapse: collapse;';
echo 'margin-top: 20px;';
echo '}';
echo 'th, td {';
echo 'border: 1px solid #ddd;';
echo 'padding: 12px;';
echo 'text-align: left;';
echo '}';
echo 'th {';
echo 'background-color: #007bff;';
echo 'color: white;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<h2>Record Management</h2>';
echo '';
echo '<!-- Form for Insert/Update -->';
echo '<form id="recordForm">';
echo '<input type="hidden" id="recordId">';
echo '<label>Title (Text):</label>';
echo '<input type="text" id="title" required placeholder="Enter item name">';
echo '<label>Quantity (Number):</label>';
echo '<input type="number" id="quantity" required placeholder="Enter quantity">';
echo '<label>Date:</label>';
echo '<input type="date" id="date" required>';
echo '<button type="submit" id="submitBtn">Save Record</button>';
echo '<button type="button" id="cancelBtn" style="display:none; background:#6c757d;">Cancel Edit</button>';
echo '</form>';
echo '';
echo '<!-- Table to Display Records -->';
echo '<table>';
echo '<thead>';
echo '<tr>';
echo '<th>Title</th>';
echo '<th>Quantity</th>';
echo '<th>Date</th>';
echo '<th>Actions</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody id="recordTableBody"></tbody>';
echo '</table>';
echo '';
echo '<script>';
echo '// --- Simulated REST API Client ---';
echo '// Maps HTTP-like methods to LocalStorage operations';
echo 'const api = {';
echo 'dbKey: 'my_app_records',';
echo '';
echo '// GET: Fetch all records';
echo 'getRecords() {';
echo 'return JSON.parse(localStorage.getItem(this.dbKey)) || [];';
echo '},';
echo '';
echo '// POST: Create a new record';
echo 'postRecord(data) {';
echo 'const records = this.getRecords();';
echo 'const newRecord = { ...data, id: Date.now().toString() };';
echo 'records.push(newRecord);';
echo 'localStorage.setItem(this.dbKey, JSON.stringify(records));';
echo 'return newRecord;';
echo '},';
echo '';
echo '// PUT: Update an existing record';
echo 'putRecord(id, updatedData) {';
echo 'const records = this.getRecords();';
echo 'const index = records.findIndex(r => r.id === id);';
echo 'if (index !== -1) {';
echo 'records[index] = { ...updatedData, id };';
echo 'localStorage.setItem(this.dbKey, JSON.stringify(records));';
echo 'return records[index];';
echo '}';
echo '},';
echo '';
echo '// DELETE: Remove a record';
echo 'deleteRecord(id) {';
echo 'const records = this.getRecords().filter(r => r.id !== id);';
echo 'localStorage.setItem(this.dbKey, JSON.stringify(records));';
echo '}';
echo '};';
echo '';
echo '// --- UI Controller ---';
echo 'const form = document.getElementById('recordForm');';
echo 'const tableBody = document.getElementById('recordTableBody');';
echo 'const submitBtn = document.getElementById('submitBtn');';
echo 'const cancelBtn = document.getElementById('cancelBtn');';
echo '';
echo '// Render data to table after every action';
echo 'function renderRecords() {';
echo 'const records = api.getRecords();';
echo 'tableBody.innerHTML = records.map(record => `';
echo '<tr>';
echo '<td>${record.title}</td>';
echo '<td>${record.quantity}</td>';
echo '<td>${record.date}</td>';
echo '<td>';
echo '<button class="edit" onclick="editRecord('${record.id}')">Edit</button>';
echo '<button class="delete" onclick="deleteRecord('${record.id}')">Delete</button>';
echo '</td>';
echo '</tr>';
echo '`).join('');';
echo '}';
echo '';
echo '// Handle Form Submission (Insert or Update)';
echo 'form.onsubmit = (e) => {';
echo 'e.preventDefault();';
echo 'const id = document.getElementById('recordId').value;';
echo 'const data = {';
echo 'title: document.getElementById('title').value,';
echo 'quantity: document.getElementById('quantity').value,';
echo 'date: document.getElementById('date').value';
echo '};';
echo '';
echo 'if (id) {';
echo 'api.putRecord(id, data); // UPDATE';
echo '} else {';
echo 'api.postRecord(data);    // INSERT';
echo '}';
echo '';
echo 'resetForm();';
echo 'renderRecords(); // DISPLAY CURRENT RECORDS';
echo '};';
echo '';
echo 'window.deleteRecord = (id) => {';
echo 'if(confirm('Delete this record?')) {';
echo 'api.deleteRecord(id);';
echo 'renderRecords(); // DISPLAY CURRENT RECORDS';
echo '}';
echo '};';
echo '';
echo 'window.editRecord = (id) => {';
echo 'const record = api.getRecords().find(r => r.id === id);';
echo 'document.getElementById('recordId').value = record.id;';
echo 'document.getElementById('title').value = record.title;';
echo 'document.getElementById('quantity').value = record.quantity;';
echo 'document.getElementById('date').value = record.date;';
echo '';
echo 'submitBtn.textContent = 'Update Record';';
echo 'cancelBtn.style.display = 'inline-block';';
echo '};';
echo '';
echo 'function resetForm() {';
echo 'form.reset();';
echo 'document.getElementById('recordId').value = '';';
echo 'submitBtn.textContent = 'Save Record';';
echo 'cancelBtn.style.display = 'none';';
echo '}';
echo '';
echo 'cancelBtn.onclick = resetForm;';
echo '';
echo '// Initial Load';
echo 'renderRecords();';
echo '</script>';
echo '</body>';
echo '</html>';
?>