<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>REST API CRUD Application</title>';
echo '<style>';
echo 'body {';
echo 'color: blue;';
echo 'background-color: aqua;';
echo 'font-family: sans-serif;';
echo 'margin: 20px;';
echo 'text-align: center;';
echo '}';
echo 'table {';
echo 'width: 100%;';
echo 'border-collapse:';
echo 'collapse; margin-top: 20px;';
echo '}';
echo 'th, td {';
echo 'border: 1px solid #ccc;';
echo 'padding: 10px;';
echo 'text-align: left;';
echo '}';
echo 'th {';
echo 'background-color: #f4f4f4;';
echo '}';
echo '.form-container {';
echo 'margin-bottom: 20px;';
echo '}';
echo 'input, button {';
echo 'padding: 8px;';
echo 'margin-top: 5px;';
echo '}';
echo 'button {';
echo 'cursor: pointer;';
echo '}';
echo '.edit-btn {';
echo 'background-color: #ffc107;';
echo '}';
echo '.delete-btn {';
echo 'background-color: #dc3545;';
echo 'color: white;';
echo '}';
echo '.add-btn {';
echo 'background-color: #28a745;';
echo 'color: white;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<h1>Records Management</h1>';
echo '';
echo '<div class="form-container">';
echo '<h2>Add/Update Record</h2>';
echo '<input type="hidden" id="record-id">';
echo '<input type="text" id="record-text" placeholder="Text Field" required>';
echo '<input type="number" id="record-number" placeholder="Number Field" required>';
echo '<input type="date" id="record-date" required>';
echo '<button onclick="saveRecord()" class="add-btn">Save Record</button>';
echo '<button onclick="cancelUpdate()" style="display: none;" id="cancel-btn">Cancel Update</button>';
echo '</div>';
echo '';
echo '<h2>Current Records</h2>';
echo '<table>';
echo '<thead>';
echo '<tr>';
echo '<th>ID</th>';
echo '<th>Text</th>';
echo '<th>Number</th>';
echo '<th>Date</th>';
echo '<th>Actions</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody id="records-table-body">';
echo '<!-- Records will be dynamically inserted here -->';
echo '</tbody>';
echo '</table>';
echo '';
echo '<script>';
echo 'const API_URL = 'https://api.example.com'; // Replace with your actual API endpoint';
echo '';
echo '// Function to fetch and display all records';
echo 'async function fetchAndDisplayRecords() {';
echo 'try {';
echo 'const response = await fetch(API_URL);';
echo 'if (!response.ok) throw new Error('Failed to fetch records');';
echo 'const records = await response.json();';
echo 'displayRecords(records);';
echo '} catch (error) {';
echo 'console.error('Error fetching records:', error);';
echo 'alert('Failed to load records. Ensure your API is running and accessible.');';
echo '}';
echo '}';
echo '';
echo '// Function to render records in the table';
echo 'function displayRecords(records) {';
echo 'const tableBody = document.getElementById('records-table-body');';
echo 'tableBody.innerHTML = '';';
echo 'records.forEach(record => {';
echo 'const row = tableBody.insertRow();';
echo 'row.innerHTML = `';
echo '<td>${record.id}</td>';
echo '<td>${record.text}</td>';
echo '<td>${record.number}</td>';
echo '<td>${new Date(record.date).toLocaleDateString()}</td>';
echo '<td>';
echo '<button onclick="editRecord('${record.id}', '${record.text}', ${record.number}, '${new Date(record.date).toISOString().split('T')[0]}')" class="edit-btn">Edit</button>';
echo '<button onclick="deleteRecord('${record.id}')" class="delete-btn">Delete</button>';
echo '</td>';
echo '`;';
echo '});';
echo '}';
echo '';
echo '// Function to save (insert/update) a record';
echo 'async function saveRecord() {';
echo 'const id = document.getElementById('record-id').value;';
echo 'const text = document.getElementById('record-text').value;';
echo 'const number = document.getElementById('record-number').value;';
echo 'const date = document.getElementById('record-date').value;';
echo '';
echo 'if (!text || !number || !date) {';
echo 'alert('All fields are required.');';
echo 'return;';
echo '}';
echo '';
echo 'const recordData = { text, number: parseInt(number), date };';
echo 'const method = id ? 'PUT' : 'POST';';
echo 'const url = id ? `${API_URL}/${id}` : API_URL;';
echo '';
echo 'try {';
echo 'const response = await fetch(url, {';
echo 'method: method,';
echo 'headers: { 'Content-Type': 'application/json' },';
echo 'body: JSON.stringify(recordData)';
echo '});';
echo '';
echo 'if (!response.ok) throw new Error('Failed to save record');';
echo '';
echo '// After each action, display the current records';
echo 'clearForm();';
echo 'fetchAndDisplayRecords();';
echo '} catch (error) {';
echo 'console.error('Error saving record:', error);';
echo 'alert('Failed to save record. Check API endpoint and implementation.');';
echo '}';
echo '}';
echo '';
echo '// Function to populate the form for editing';
echo 'function editRecord(id, text, number, date) {';
echo 'document.getElementById('record-id').value = id;';
echo 'document.getElementById('record-text').value = text;';
echo 'document.getElementById('record-number').value = number;';
echo 'document.getElementById('record-date').value = date;';
echo 'document.getElementById('cancel-btn').style.display = 'inline';';
echo '}';
echo '';
echo '// Function to delete a record';
echo 'async function deleteRecord(id) {';
echo 'if (!confirm('Are you sure you want to delete this record?')) return;';
echo '';
echo 'try {';
echo 'const response = await fetch(`${API_URL}/${id}`, {';
echo 'method: 'DELETE'';
echo '});';
echo '';
echo 'if (!response.ok) throw new Error('Failed to delete record');';
echo '';
echo '// After each action, display the current records';
echo 'fetchAndDisplayRecords();';
echo '} catch (error) {';
echo 'console.error('Error deleting record:', error);';
echo 'alert('Failed to delete record. Check API endpoint and implementation.');';
echo '}';
echo '}';
echo '';
echo '// Function to clear the input form';
echo 'function clearForm() {';
echo 'document.getElementById('record-id').value = '';';
echo 'document.getElementById('record-text').value = '';';
echo 'document.getElementById('record-number').value = '';';
echo 'document.getElementById('record-date').value = '';';
echo 'document.getElementById('cancel-btn').style.display = 'none';';
echo '}';
echo '';
echo 'function cancelUpdate() {';
echo 'clearForm();';
echo '}';
echo '';
echo '// Initial fetch of records when the page loads';
echo 'document.addEventListener('DOMContentLoaded', fetchAndDisplayRecords);';
echo '</script>';
echo '</body>';
echo '</html>';
?>