<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Storm Data Analyzer</title>';
echo '<style>';
echo 'body {';
echo 'color: blue;';
echo 'background-color: aqua;';
echo 'font-family: sans-serif;';
echo 'margin: 20px;';
echo 'text-align: center;';
echo '}';
echo 'table {';
echo 'border-collapse: collapse;';
echo 'width: 100%;';
echo 'margin-top: 20px;';
echo '}';
echo 'th, td {';
echo 'border: 1px solid #ddd;';
echo 'padding: 8px;';
echo 'text-align: left;';
echo '}';
echo 'th {';
echo 'background-color: #f2f2f2;';
echo '}';
echo '/* Color coding for categories */';
echo '.cat-Tropical_Storm { background-color: #add8e6; } /* Light Blue */';
echo '.cat-1 { background-color: #ffeb9c; } /* Light Yellow */';
echo '.cat-2 { background-color: #ffc; }    /* Yellow */';
echo '.cat-3 { background-color: #ffaa4c; } /* Orange */';
echo '.cat-4 { background-color: #ff7f50; } /* Coral */';
echo '.cat-5 { background-color: #ff4500; } /* OrangeRed */';
echo '.cat-Tropical_Depression { background-color: #e0e0e0; } /* Light Gray */';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<h2>Upload Storm Data CSV</h2>';
echo '';
echo '<form action="storm_tracker.php" method="post" enctype="multipart/form-data">';
echo 'Select CSV file to upload:';
echo '<input type="file" name="stormFile" id="stormFile" accept=".csv">';
echo '<input type="submit" value="Upload and Analyze" name="submit">';
echo '</form>';
echo '';
echo '<?php';
echo '// --- Configuration and Functions ---';
echo '';
echo '/**';
echo '* Converts kilometers per hour (kph) to miles per hour (mph).';
echo '* The conversion factor is approximately 0.621371.';
echo '* @param float $kph Wind speed in kph.';
echo '* @return float Wind speed in mph.';
echo '*/';
echo 'function kphToMph($kph) {';
echo 'return $kph * 0.621371;';
echo '}';
echo '';
echo '/**';
echo '* Determines the Saffir-Simpson category based on wind speed in kph.';
echo '* Scale information from the [NOAA Hurricane Center](https://www.nhc.noaa.gov/aboutsshws.php).';
echo '* @param float $kph Wind speed in kph.';
echo '* @return string The category or classification.';
echo '*/';
echo 'function getSaffirSimpsonCategory($kph) {';
echo 'if ($kph >= 252) {';
echo 'return '5'; // 252 km/h or higher';
echo '} elseif ($kph >= 209) {';
echo 'return '4'; // 209-251 km/h';
echo '} elseif ($kph >= 178) {';
echo 'return '3'; // 178-208 km/h';
echo '} elseif ($kph >= 154) {';
echo 'return '2'; // 154-177 km/h';
echo '} elseif ($kph >= 119) {';
echo 'return '1'; // 119-153 km/h';
echo '} elseif ($kph >= 63) {';
echo 'return 'Tropical Storm'; // 63-117 km/h';
echo '} else {';
echo 'return 'Tropical Depression'; // 0-62 kph';
echo '}';
echo '}';
echo '';
echo '// --- Main Logic ---';
echo '';
echo 'if (isset($_POST['submit']) && isset($_FILES['stormFile'])) {';
echo '$file = $_FILES['stormFile']['tmp_name'];';
echo '';
echo 'if (($handle = fopen($file, "r")) !== FALSE) {';
echo '$storms = [];';
echo '$header = fgetcsv($handle); // Skip header row';
echo '';
echo 'while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {';
echo '// Assuming CSV columns are Date, Storm Name, Max Sustained Winds (kph)';
echo 'if (count($data) >= 3) {';
echo '$kph = (float)$data[2];';
echo '$storms[] = [';
echo ''date' => $data[0],';
echo ''name' => $data[1],';
echo ''kph' => $kph,';
echo ''mph' => round(kphToMph($kph), 2),';
echo ''category' => getSaffirSimpsonCategory($kph)';
echo '];';
echo '}';
echo '}';
echo 'fclose($handle);';
echo '';
echo '// Sort data by wind intensity in decreasing order (highest wind first)';
echo 'usort($storms, function ($a, $b) {';
echo 'return $b['kph'] <=> $a['kph'];';
echo '});';
echo '';
echo '// Display the data';
echo 'echo "<h3>Analyzed Storm Data (Sorted by Intensity)</h3>";';
echo 'echo "<table>";';
echo 'echo "<thead><tr><th>Date</th><th>Storm Name</th><th>Max Winds (kph)</th><th>Max Winds (mph)</th><th>Category</th></tr></thead>";';
echo 'echo "<tbody>";';
echo '';
echo 'foreach ($storms as $storm) {';
echo '// Create a CSS class name from the category (e.g., 'Tropical Storm' becomes 'cat-Tropical_Storm')';
echo '$categoryClass = 'cat-' . str_replace(' ', '_', $storm['category']);';
echo 'echo "<tr class='{$categoryClass}'>";';
echo 'echo "<td>" . htmlspecialchars($storm['date']) . "</td>";';
echo 'echo "<td>" . htmlspecialchars($storm['name']) . "</td>";';
echo 'echo "<td>" . htmlspecialchars($storm['kph']) . "</td>";';
echo 'echo "<td>" . htmlspecialchars($storm['mph']) . "</td>";';
echo 'echo "<td>" . htmlspecialchars($storm['category']) . "</td>";';
echo 'echo "</tr>";';
echo '}';
echo '';
echo 'echo "</tbody>";';
echo 'echo "</table>";';
echo '';
echo '} else {';
echo 'echo "<p style='color: red;'>Error opening the uploaded file.</p>";';
echo '}';
echo '} elseif (isset($_POST['submit'])) {';
echo 'echo "<p style='color: red;'>File upload failed. Please try again.</p>";';
echo '}';
echo '?>';
echo '';
echo '</body>';
echo '</html>';
?>